# 실행시 필요한 인자 : TAG(springboot version), GRAFANA_PW(그라파나 비밀번호)
# 실행 명령어 : TAG=1.13 GRAFANA_PW=123456 docker-compose -f compose-public up -d

version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "9111:9111"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx-cache:/data/nginx/cache
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./logs/nginx:/var/log/nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on :
      - api-1
      - api-2
    restart: always
    networks:
      - app-network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - -nginx.scrape-uri=http://nginx:9111/stub_status
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    networks:
      - app-network

  api-1:
    image: ghcr.io/jmsuper/finance:${TAG:-latest}
    container_name: api-1
    environment:
      - SPRING_PROFILES_ACTIVE=api
    ports:
      - "8080"
      - "8001:8000"
    volumes:
      - ${PWD}/logs/api-1:/var/log/finance
    restart: always
    extra_hosts:
      - "snowball-stock.site:10.10.0.4"
    networks:
      - app-network

  api-2:
    image: ghcr.io/jmsuper/finance:${TAG:-latest}
    container_name: api-2
    environment:
      - SPRING_PROFILES_ACTIVE=api
    ports:
      - "8080"
      - "8002:8000"
    volumes:
      - ${PWD}/logs/api-2:/var/log/finance
    restart: always
    extra_hosts:
      - "snowball-stock.site:10.10.0.4"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge