scrape_configs:
  - job_name: 'spring-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['api-1:8000', 'api-2:8000']

  - job_name: 'spring-scheduler'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.1.4:8000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9500']

  - job_name: 'redis'
    static_configs:
      - targets: ['10.10.1.4:9500']

#  - job_name: 'mysql'
#    static_configs:
#      - targets: ['mysql-exporter:9104']